'use strict';
const assert = require('node:assert');
const { createBooking, releaseFunds, refund, demoCommission } = require('./bookingEscrow');
const held = createBooking({ spotId: 'spot-1', hostId: 'host-1', driverId: 'driver-1', priceIls: 40, windowMins: 60 });
assert.strictEqual(held.status, 'held');
assert.strictEqual(held.paymentMode, 'demo');
assert.throws(() => releaseFunds(held, 3_599_999), /not elapsed/);
assert.strictEqual(releaseFunds(held, 3_600_000).status, 'released');
assert.strictEqual(refund(held).status, 'refunded');
assert.strictEqual(demoCommission(40, { launch: true }), 0);
assert.strictEqual(demoCommission(40), 6);
assert.throws(() => createBooking({}), /spotId/);
assert.throws(() => demoCommission(-1), /positive/);
console.log('bookingEscrow: all assertions passed');
